※변수 정의:
int 정수
float 소수점 표현
string 문자
list 나열

In [9]:
a=1; print(type(a))

<class 'int'>


In [12]:
a = 1; a = float(a); print(type(a))

<class 'float'>


In [13]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


string으로 표현할때 글자 각각의 위치는 x[0]부터 시작 (-1은 마지막번째)

In [14]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


list함수는 [대괄호]로 표현됨

In [15]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


In [16]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


tuple함수는 여러 요소들의 집합

In [17]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


dict함수-dictionary에서 파생, ':'의 형태로 표현

In [18]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


In [20]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

a의 부분요소를 i로

In [21]:
a = [1, 2, 3, 4]
for i in a:
    print(i)

1
2
3
4


※len(a)=4, range(4)=위치 0,1,2,3

In [23]:
a = [1, 2, 3, 4]
for i in range(len(a)):
    print(i+1)

1
2
3
4


In [24]:
a = ['red', 'green', 'blue', 'purple']
for i in a:
    print(i)

red
green
blue
purple


In [25]:
a = ['red', 'green', 'blue', 'purple']
for i in range(len(a)):
    print(a[i])

red
green
blue
purple


i=0,1,2,3 <- a의 위치값

In [26]:
a = ["red", "green", "blue", "purple"]
b = [0.2, 0.3, 0.1, 0.4]
for i, a in enumerate(a):
    print("{}: {}%".format(a, b[i]*100))

red: 20.0%
green: 30.0%
blue: 10.0%
purple: 40.0%


a,b를 합쳐서 loop

In [33]:
a = ["red", "green", "blue", "purple"]
b = [0.2, 0.3, 0.1, 0.4]
for a_, b_ in zip(a, b):
    print("{}: {}%".format(a_, b_*100))

red: 20.0%
green: 30.0%
blue: 10.0%
purple: 40.0%


변수 assign의 경우에만 "="사용, 그 외에는 "=="

In [34]:
a = 0
if a == 0:
    print(a)
else:
     print(a+1)

0


range(1,3)=1,2  
range(3,5)=3,4

In [35]:
for i in range(1, 3):
    for j in range(3, 5):
        print(i*j)

3
4
6
8


In [36]:
for i in range(1, 3):
    for j in range(3, 5):
        if j >=4:
            print(i*j)

4
8


In [37]:
a = [1, 2, 3, 4]
b = [i for i in a if i >=2]
b

[2, 3, 4]

글자수가 4 이상인것

In [38]:
a = ['red', 'green', 'blue', 'purple']
b = [i for i in a if len(i) >=4]
b

['green', 'blue', 'purple']

numpy:디렉터리에 있는 모든걸 띄워라. (importy때문에 시간 소요됨).
array: 행렬(matrix) 비스무리한거

In [50]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

In [44]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


수학에서의 행렬은 아니기 때문에 (2x3)(2x3)계산이 됨

In [45]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


따라서 c를 행렬(matrix)로 변수정의한다면 계산x

In [51]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [52]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

Transform을 통해 (2x3)을 (3x2)로 변환--> 계산가능{∵(2x3)(3x2)}

In [53]:
c*c.T

matrix([[14, 19],
        [19, 73]])

In [54]:
s = 'abcdef'
print(s[0], s[5], s[-1], s[-6])
print(s[1:3], s[1:], s[:3], s[:])

a f f a
bc bcdef abc abcdef


In [55]:
len(s)

6

In [56]:
s[1]+s[3]+s[4:]*10

'bdefefefefefefefefefef'

In [58]:
s.upper()

'ABCDEF'

In [74]:
s = ' this is a house built this year.\n' 	
s

' this is a house built this year.\n'

????????????? strip: similar to exel 'trim'

In [72]:
s = s.strip()
s

AttributeError: 'builtin_function_or_method' object has no attribute 'strip'

In [65]:
len(s)

34

house가 있는 point 출력 (left most)

In [64]:
result=s.find('house')
result

11

right most search

In [67]:
result=s.rindex('this')
result

23

In [73]:
tokens = s.split(' ')
tokens

AttributeError: 'builtin_function_or_method' object has no attribute 'split'

In [76]:
s = s.replace('this', 'that')
s

' that is a house built that year.\n'